Read addonlist.txt
pukmajster/funky pull request #16
Opened 2024-09-12 09:36 UTC by MerryDreambound

Adds an dev button that reads the addonlist.txt and uses regex to extract data from it and update the enabled addons db.
Current issues:
- Not integrated with on boarding.
- It's on a dev settings location, which may confuse users.
- Overwrites profile data (Maybe we should use a currently active addons profile, to not overwrite profiles when used)

Closes #7

2024-09-16 23:14 UTC, MerryDreambound commented
The first initial commits, are me getting used to the code base/testing stuff out, so sorry if it's messy

2024-09-19 12:21 UTC, pukmajster requested changes
Looks like workshop directories ("/workshop/x.vpk") are hardcoded, which means locally installed addons present in "/addons/" will be ignored entirely. Let me know if you can whip up a fix for that.

2024-09-19 20:27 UTC, MerryDreambound commented
I'll check up on that when I have the time, thank you

2024-10-15 18:43 UTC, pukmajster commented
Sorry for the lack of updates on this - i'll be taking a look tomorrow!

2024-10-16 17:57 UTC, MerryDreambound commented
Don't worry about it

2024-10-16 18:19 UTC, pukmajster commented
I adjust how Funky gets the metadata for mods. Workshop mods now get their data from the Workshop API directly, while the traditional method of reading the VPK's addoninfo.txt remains for mods installed outside of the Workshop.

While this is not a full fix, it will fix all Workshop mods from crashing Funky. Expect the update tomorrow along with some other smaller goodies!

2024-10-16 18:40 UTC, pukmajster commented
Alright, looks good! This will ship with v0.3.0 that implements this feature into the onboarding experience

2024-10-16 18:40 UTC, merged

2024-10-16 23:57 UTC, pukmajster commented
The update is out with the updated onboarding. Again, sorry for the wait. I appreciate the lovely work you've done though!